name: Makefile CI

on:
  push:
    branches:
      - "main"
      - "v*.*"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: autogen
      run: autoreconf --install --force

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssh-dev libsystemd-dev
          
    - name: configure
      run: ./configure

    - name: Run make
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
